sudo: required
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker-compose build
  - docker-compose up web
  - script/in_docker rake db:setup
script:
  - script/in_docker rake
