db:
  image: postgres:9.4.1
  ports:
    - "5433:5432"
box:
  image: busybox
  volumes:
    - /box
web:
  build: .
  ports:
    - "5000:5000"
  links:
    - db
  volumes:
    - .:/app
  volumes_from:
    - box
