version: "3.8"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  box:
    image: busybox
    volumes:
      - /box
  web:
    build: .
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: postgres
    ports:
      - "3000:3000"
    links:
      - postgres
    volumes:
      - .:/app
    volumes_from:
      - box
