development: &default
  adapter: postgresql
  database: onruby_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db
  port: 5432
  encoding: utf8

test:
  <<: *default
  database: onruby_test
  username: postgres
  host: localhost

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
